[package]
name = "crackle-kit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["chrono","env-filter"] }
